name: Lint

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: wow-lint
        uses: davidcraig/action-wow-lint@1.0.0
        with:
            path-to-files: 'cargofmt.lua'
