name: Lint

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: nebularg/actions-luacheck@v1
        with:
          path: '.'
          args: '-o 011'
          annotate: 'error'
